---
- name: Configuração do NFS
  hosts: all
  become: yes
  tasks:
    - name: Instalar pacotes NFS
      apt:
        name:
          - nfs-kernel-server
        state: present

    - name: Criar o diretório /dados/nfs
      file:
        path: /dados/nfs
        state: directory
        owner: nfs-ifpb
        group: nfs-ifpb
        mode: '0755'

    - name: Configurar exportação do diretório NFS
      lineinfile:
        path: /etc/exports
        line: "/dados/nfs 192.168.57.0/24(rw,sync,no_subtree_check)"

    - name: Reiniciar o serviço NFS
      service:
        name: nfs-kernel-server
        state: restarted
        enabled: yes

