---
- name: Configuração do Sudo
  hosts: all
  become: yes
  tasks:
    - name: Adicionar o grupo ifpb ao arquivo sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^%ifpb'
        line: '%ifpb ALL=(ALL) NOPASSWD: ALL'

