---
- name: Monitoramento de acesso
  hosts: all
  become: yes
  tasks:
    - name: Criar o diretório para armazenar os logs de acesso
      file:
        path: /dados/nfs
        state: directory
        mode: '0755'

    - name: Configurar o auditd para registrar logins
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: "-w /var/log/auth.log -p wa -k monitoramento_acesso"
        create: yes

    - name: Reiniciar o serviço auditd para aplicar regras
      service:
        name: auditd
        state: restarted